### PR TITLE
RVGM added extra systems/languages/animations

### PR DESCRIPTION
**Pull request by virtual-man007**
…Retrobat based Retro-Bliss LevelUp Project.
Please update info.png accordingly

PSP
Playstation Portable Minis

PSVita
Playstation Vita

Teknoparrot
Arcade Game / Coin-OP

Visual Pinball
Pinball Game Engine

Additions:

additional system support
additional language EN files/updates
additional sprites and animation support
more to come ...
Signed-off-by: virtualman

### CODE REVIEW

**Comment by virtual-man007** [comment]
Any ETA to get this commited and get those 4 info.png ? It's been near a month

**Comment by Darknior** [comment]
> Any ETA to get this commited and get those 4 info.png ? It's been near a month

Sorry i'm in vacations, i will do it as fast as i can. Thanks for your work,

**Comment by virtual-man007** [comment]
Any ETA, status?

**Comment by Darknior** [comment]
Hi @virtual-man007 
I have finally work again on my theme and add all the systems missing for Retrobat.
I've not accept your PR because you have push so many systems at same time and there where so many errors :(
I was never agree with the background and the avatar. You have always made the same animation with smoke and light ... we plan to make a different one by system. And i have draw better like i like, a differnt game by system.
I have also double some systems for you like Genesis and MegaCD, Tg16 etc ... and put the fines info and images for them.
And in some others i have added PT info images to feet what you want.
Thanks for your help on some things i ve user ...
Now if you want you can translate my english text in other languages ...
And if you have some other ideas you are welcome to help us
see you

**Comment by Darknior** [comment]
https://github.com/Darknior/RVGM-BT-Theme/commit/d88c45f3d0abc8c838b96868c694efbd6a280193

**Pull request closed without merging**
